name: Deploy Docs
on:
  push:
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1

      - name: Build & Deploy
        run: sh deploy-docs.sh ${{ secrets.ACCESS_TOKEN }}
