name: Build Docs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Setup Node.js
      uses: actions/setup-node@v3.8.1

    - name: Build
      run: sh deploy.sh
      
    - name: test
      run: ls docs
