name: Build Docs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Setup Node.js
      uses: actions/setup-node@v3.8.1

    - name: Build
      shell: bash
      working-directory: docs
      run: yarn install && rm -rf ./.vuepress/dict && export NODE_OPTIONS=--openssl-legacy-provider && yarn vuepress build .
      
    - name: test
      run: echo "$PWD"

    - name: Push to gh-pages
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${ secrets.GITHUB_TOKEN }
        branch: gh-pages
        directory: docs/.vuepress/dict
