name: Build Docs
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Setup Node.js
      uses: actions/setup-node@v3.8.1

    - name: Build
      shell: cmd
      working-directory: docs
      run: |
        yarn install
        yarn run docs:build

    - name: Push to gh-pages
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${ secrets.GITHUB_TOKEN }
        branch: gh-pages
        directory: docs/.vuepress/dict
